CREATE USER 'aibot'@'localhost' IDENTIFIED BY  'aibot';
GRANT USAGE ON * . * TO  'aibot'@'localhost' IDENTIFIED BY  'aibot' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
CREATE DATABASE IF NOT EXISTS  `aibot` ;
GRANT ALL PRIVILEGES ON  `aibot` . * TO  'aibot'@'localhost';
